server:
  url: ${server.domain}:${server.port}

spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

  # Flyway
  flyway:
    enabled: false
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

# Eureka Client
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
