FROM eclipse-temurin:17-jre

ARG SERVICE_DIR
WORKDIR /skladmarket

ENV JAVA_OPTS=""

COPY ${SERVICE_DIR}/build/libs/${SERVICE_DIR}.jar /skladmarket/skladmarket.jar

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /skladmarket/skladmarket.jar"]
