FROM eclipse-temurin:17-jdk AS build

ARG SERVICE_DIR
LABEL authors="Xojiakbar"
WORKDIR /workspace

COPY ${SERVICE_DIR}/gradlew ./gradlew
COPY ${SERVICE_DIR}/gradle ./gradle
COPY ${SERVICE_DIR}/build.gradle ./build.gradle
COPY ${SERVICE_DIR}/settings.gradle ./settings.gradle

RUN chmod +x ./gradlew
COPY ${SERVICE_DIR}/src ./src

RUN ./gradlew bootJar -x test --no-daemon
RUN JAR_FILE=$(find build/libs -type f -name "*.jar" ! -name "*plain.jar" | head -n 1) && cp "$JAR_FILE" /workspace/skladmarket.jar

FROM eclipse-temurin:17-jre

WORKDIR /skladmarket

ENV JAVA_OPTS=""

COPY --from=build /workspace/skladmarket.jar /skladmarket/skladmarket.jar

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /skladmarket/skladmarket.jar"]

