server:
#  address: 0.0.0.0
  port: ${SERVER_PORT:8761}

spring:
  application:
    name: discovery-service

eureka:
#  instance:
#    hostname: ${EUREKA_HOST:}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka/}
