server:
  address: 0.0.0.0
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true

      routes:
        # Auth Service
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/v1/auth/**
        # User Service
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**,/api/v1/location/**,/api/v1/admin/users,/api/v1/admin/users/**,/api/v1/location

        # Company Service
        - id: company-service
          uri: lb://company-service
          predicates:
            - Path=/api/v1/companies,/api/v1/companies/**,/api/v1/admin/companies,/api/v1/admin/companies/**,/api/v1/company-favorites,/api/v1/company-favorites/**
        #Category
        - id: category-service
          uri: lb://category-service
          predicates:
            - Path=/api/v1/categories,/api/v1/categories/**,/api/v1/admin/categories,/api/v1/admin/categories/**
        #Product
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/v1/products,/api/v1/products/**,/api/v1/product-favorites,/api/v1/product-favorites/**,/api/v1/catalog,/api/v1/catalog/**,/api/v1/admin/products,/api/v1/admin/products/**,/api/v1/admin/banners,/api/v1/admin/banners/**
        #Lead
        - id: lead-service
          uri: lb://lead-service
          predicates:
            - Path=/api/v1/leads,/api/v1/leads/**,/api/v1/leads/cancel**,/api/v1/cart,/api/v1/cart/**
        # Chat REST
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/v1/chats,/api/v1/chats/**,/api/v1/support/**,/api/v1/admin/support/**
        # Chat WebSocket
        - id: chat-service-ws
          uri: lb:ws://chat-service
          predicates:
            - Path=/api/v1/ws/chat,/api/v1/ws/chat/**,/api/v1/ws/support,/api/v1/ws/support/**
        # Notification
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/v1/notifications,/api/v1/notifications/**
        # Report
        - id: report-service
          uri: lb://report-service
          predicates:
            - Path=/api/v1/reports,/api/v1/reports/**,/api/v1/admin/reports,/api/v1/admin/reports/**,/api/v1/admin/dashboard,/api/v1/seller/dashboard,/api/v1/seller/dashboard/**
        # File
        - id: file-service
          uri: lb://file-service
          predicates:
            - Path=/api/v1/attach/**
        # AI
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/api/v1/ai/**
eureka:
  client:
    service-url:
#      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://127.0.0.1:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:false}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}
    instance-id: ${spring.application.name}:${server.port}

