server:
  url: ${server.domain}:${server.port}

spring:
  application:
    name: chat-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

media:
  base-url: ${aws.url}/${aws.bucket-name}

chat:
  websocket:
    token-expiration-second: 60
    token-secret: change-this-chat-websocket-secret-in-production
